network:
  version: 2
  renderer: networkd
  wifis:
    wlp3s0:
      dhcp4: no
      addresses: [192.168.29.100/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.29.1
          metric: 100
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      optional: true
